### ISSUE TITLE
Add FastFlow, a new Anomaly Detector

### ISSUE THREAD

**Issue by innat** [open-edge-platform/anomalib#114]
**Is your feature request related to a problem? Please describe.**

  - New sota: https://paperswithcode.com/sota/anomaly-detection-on-mvtec-ad
  - paper: https://arxiv.org/pdf/2111.07677v2.pdf

**Comment by bmabir17-asj** [comment]
- unofficial implementation (WIP) : https://github.com/AlessioGalluccio/FastFlow

**Comment by samet-akcay** [comment]
We already have a [branch](https://github.com/openvinotoolkit/anomalib/tree/feature/fastflow) to implement it, but it's still in WiP. 

We welcome contributions to the branch. Those who would like to contribute could create a new branch from `feature/fastflow` and create a pull request to this branch.

```
git clone https://github.com/openvinotoolkit/anomalib.git
git checkout feature/fastflow
git checkout -b <name-of-your-branch-to-work-on>
...
# Work on your implementation/changes
...
# Create a PR to feature/fastflow
```

Thanks!

**Comment by innat** [comment]
@samet-akcay Thanks for this information. We're currently working on fastflow, would love to contribute when it's ready.

**Comment by mjack3** [comment]
Did you any progress? I opened my fastflow implementation in my github (wip). The paper is very obscure

**Comment by samet-akcay** [comment]
Not yet. Unfortunately, we've been packed with other tasks that we couldn't find time to work on this
