### ISSUE TITLE
[Task]: RuntimeError: Found 0 normal images in /content/drive/MyDrive/EfficientAD/anomalib/datasets/original/screw/train/good

### ISSUE THREAD

**Issue by kmymch** [open-edge-platform/anomalib#1554]
### What is the motivation for this task?

I tried to train my original dataset by EfficientAD model, but I got this error message. I thought it was wrong that I used shared folder as dataset folder, and I copied in my drive. However, the same problem has been remaining. 

### Describe the solution you'd like

I want to train my own dataset.

**Comment by blaz-r** [comment]
Hello. This error message can also occur if your path is wrong, it does not necessarily mean that your images are not detected. Can you verify that the path to files is exactly `/content/drive/MyDrive/EfficientAD/anomalib/datasets/original/screw/train/good`

**Comment by abc-125** [comment]
Hello, it is also possible that you have a file extension different from the default ones  `".jpg", ".jpeg", ".png", ".ppm", ".bmp", ".pgm", ".tif", ".tiff", ".webp"`. In that case, you can add your extension to the config file, `extensions: .ext`.

**Comment by abc-125** [comment]
You're welcome! In the config file, you can use `extensions: [.ext1, .ext2, ...]` to handle different extensions.
