### ISSUE TITLE
[Task]: Custom dataset

### ISSUE THREAD

**Issue by Sam-khanjani** [open-edge-platform/anomalib#2103]
### What is the motivation for this task?

the Custom Dataset tutorial file in this link https://github.com/openvinotoolkit/anomalib/blob/main/docs/source/markdown/guides/how_to/data/custom_data.md
has some problem!!
we cannot see python or yaml files.

### Describe the solution you'd like

Please add correct codes inside each section.

**Comment by samet-akcay** [comment]
Hi @hesamkh1, it does not have a problem, that is the raw documentation file. Here is the actual documentation built via sphinx
https://anomalib.readthedocs.io/en/latest/markdown/guides/how_to/data/custom_data.html
